version: '3.8'

services:
  dev:
    container_name: crud-nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    networks:
      - nestjs-network
    depends_on:
      - mongo
  prod:
    container_name: crud-nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:prod
    networks:
      - nestjs-network
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 21017:2107
    networks:
      - nestjs-network
    restart: always
    volumes:
      - mongodata:/data/db

networks:
  nestjs-network:
volumes:
  mongodata:  